// <auto-generated />
using IRSv2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRSv2._0.Migrations
{
    [DbContext(typeof(IRSDbContext))]
    [Migration("20250126154509_newDataBase")]
    partial class newDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CooksModelOrdersModel", b =>
                {
                    b.Property<string>("CooksID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CooksID", "OrdersID");

                    b.HasIndex("OrdersID");

                    b.ToTable("CooksOrders", (string)null);
                });

            modelBuilder.Entity("CooksModelToGoOrdersModel", b =>
                {
                    b.Property<string>("CooksID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToGoOrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CooksID", "ToGoOrdersID");

                    b.HasIndex("ToGoOrdersID");

                    b.ToTable("CooksToGoOrders", (string)null);
                });

            modelBuilder.Entity("IRSv2._0.Models.CooksModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Cooks");
                });

            modelBuilder.Entity("IRSv2._0.Models.DeliverersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Deliverers");
                });

            modelBuilder.Entity("IRSv2._0.Models.HostsModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("IRSv2._0.Models.ManagersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("IRSv2._0.Models.OrdersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WaiterID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("TableID")
                        .IsUnique()
                        .HasFilter("[TableID] IS NOT NULL");

                    b.HasIndex("WaiterID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IRSv2._0.Models.ProductsModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IRSv2._0.Models.StorageItemsModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StorageItems");
                });

            modelBuilder.Entity("IRSv2._0.Models.TablesModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WaiterID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("HostID");

                    b.HasIndex("WaiterID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("IRSv2._0.Models.ToGoOrdersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DelivererID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverPhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DelivererID");

                    b.HasIndex("HostID");

                    b.ToTable("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.WaitersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnWork")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Waiters");
                });

            modelBuilder.Entity("OrdersModelProductsModel", b =>
                {
                    b.Property<string>("OrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductsID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrdersID", "ProductsID");

                    b.HasIndex("ProductsID");

                    b.ToTable("ProductsOrders", (string)null);
                });

            modelBuilder.Entity("ProductsModelStorageItemsModel", b =>
                {
                    b.Property<string>("ItemsID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductsID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ItemsID", "ProductsID");

                    b.HasIndex("ProductsID");

                    b.ToTable("StorageItemsProducts", (string)null);
                });

            modelBuilder.Entity("ProductsModelToGoOrdersModel", b =>
                {
                    b.Property<string>("ProductsID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToGoOrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductsID", "ToGoOrdersID");

                    b.HasIndex("ToGoOrdersID");

                    b.ToTable("ProductsToGoOrders", (string)null);
                });

            modelBuilder.Entity("CooksModelOrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.CooksModel", null)
                        .WithMany()
                        .HasForeignKey("CooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.OrdersModel", null)
                        .WithMany()
                        .HasForeignKey("OrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CooksModelToGoOrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.CooksModel", null)
                        .WithMany()
                        .HasForeignKey("CooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.ToGoOrdersModel", null)
                        .WithMany()
                        .HasForeignKey("ToGoOrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IRSv2._0.Models.CooksModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ManagersModel", "Manager")
                        .WithMany("Cooks")
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IRSv2._0.Models.DeliverersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ManagersModel", "Manager")
                        .WithMany("Deliverers")
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IRSv2._0.Models.HostsModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ManagersModel", "Manager")
                        .WithMany("Hosts")
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IRSv2._0.Models.OrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.TablesModel", "Table")
                        .WithOne("Order")
                        .HasForeignKey("IRSv2._0.Models.OrdersModel", "TableID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IRSv2._0.Models.WaitersModel", "Waiter")
                        .WithMany("Orders")
                        .HasForeignKey("WaiterID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Table");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("IRSv2._0.Models.TablesModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.HostsModel", "Host")
                        .WithMany("Sector")
                        .HasForeignKey("HostID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IRSv2._0.Models.WaitersModel", "Waiter")
                        .WithMany("Sector")
                        .HasForeignKey("WaiterID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Host");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("IRSv2._0.Models.ToGoOrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.DeliverersModel", "Deliverer")
                        .WithMany("ToGoOrders")
                        .HasForeignKey("DelivererID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IRSv2._0.Models.HostsModel", "Host")
                        .WithMany("ToGoOrders")
                        .HasForeignKey("HostID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Deliverer");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("IRSv2._0.Models.WaitersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ManagersModel", "Manager")
                        .WithMany("Waiters")
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("OrdersModelProductsModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.OrdersModel", null)
                        .WithMany()
                        .HasForeignKey("OrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.ProductsModel", null)
                        .WithMany()
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsModelStorageItemsModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.StorageItemsModel", null)
                        .WithMany()
                        .HasForeignKey("ItemsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.ProductsModel", null)
                        .WithMany()
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsModelToGoOrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ProductsModel", null)
                        .WithMany()
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.ToGoOrdersModel", null)
                        .WithMany()
                        .HasForeignKey("ToGoOrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IRSv2._0.Models.DeliverersModel", b =>
                {
                    b.Navigation("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.HostsModel", b =>
                {
                    b.Navigation("Sector");

                    b.Navigation("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.ManagersModel", b =>
                {
                    b.Navigation("Cooks");

                    b.Navigation("Deliverers");

                    b.Navigation("Hosts");

                    b.Navigation("Waiters");
                });

            modelBuilder.Entity("IRSv2._0.Models.TablesModel", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();
                });

            modelBuilder.Entity("IRSv2._0.Models.WaitersModel", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sector");
                });
#pragma warning restore 612, 618
        }
    }
}
