// <auto-generated />
using IRSv2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRSv2._0.Migrations
{
    [DbContext(typeof(IRSDbContext))]
    [Migration("20250125114910_switchToAdi")]
    partial class switchToAdi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CooksModelOrdersModel", b =>
                {
                    b.Property<string>("CooksID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CooksID", "OrdersID");

                    b.HasIndex("OrdersID");

                    b.ToTable("CooksModelOrdersModel");
                });

            modelBuilder.Entity("CooksModelToGoOrdersModel", b =>
                {
                    b.Property<string>("CooksID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToGoOrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CooksID", "ToGoOrdersID");

                    b.HasIndex("ToGoOrdersID");

                    b.ToTable("CooksModelToGoOrdersModel");
                });

            modelBuilder.Entity("IRSv2._0.Models.CooksModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagersModelID");

                    b.ToTable("Cooks");
                });

            modelBuilder.Entity("IRSv2._0.Models.DeliverersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagersModelID");

                    b.ToTable("Deliverers");
                });

            modelBuilder.Entity("IRSv2._0.Models.HostsModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagersModelID");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("IRSv2._0.Models.ManagersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("IRSv2._0.Models.OrdersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("TableID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaiterID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaitersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("WaitersModelID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IRSv2._0.Models.ProductsModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ToGoOrdersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrdersModelID");

                    b.HasIndex("ToGoOrdersModelID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IRSv2._0.Models.StorageItemsModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductsModelID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProductsModelID");

                    b.ToTable("StorageItems");
                });

            modelBuilder.Entity("IRSv2._0.Models.TablesModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostsModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WaitersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("HostsModelID");

                    b.HasIndex("OrderId");

                    b.HasIndex("WaitersModelID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("IRSv2._0.Models.ToGoOrdersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeliverersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostsModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverPhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DeliverersModelID");

                    b.HasIndex("HostsModelID");

                    b.ToTable("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.WaitersModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagersModelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnWork")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ManagersModelID");

                    b.ToTable("Waiters");
                });

            modelBuilder.Entity("CooksModelOrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.CooksModel", null)
                        .WithMany()
                        .HasForeignKey("CooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.OrdersModel", null)
                        .WithMany()
                        .HasForeignKey("OrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CooksModelToGoOrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.CooksModel", null)
                        .WithMany()
                        .HasForeignKey("CooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.ToGoOrdersModel", null)
                        .WithMany()
                        .HasForeignKey("ToGoOrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IRSv2._0.Models.CooksModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ManagersModel", null)
                        .WithMany("Cooks")
                        .HasForeignKey("ManagersModelID");
                });

            modelBuilder.Entity("IRSv2._0.Models.DeliverersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ManagersModel", null)
                        .WithMany("Deliverers")
                        .HasForeignKey("ManagersModelID");
                });

            modelBuilder.Entity("IRSv2._0.Models.HostsModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ManagersModel", null)
                        .WithMany("Hosts")
                        .HasForeignKey("ManagersModelID");
                });

            modelBuilder.Entity("IRSv2._0.Models.OrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.WaitersModel", null)
                        .WithMany("Orders")
                        .HasForeignKey("WaitersModelID");
                });

            modelBuilder.Entity("IRSv2._0.Models.ProductsModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.OrdersModel", null)
                        .WithMany("Products")
                        .HasForeignKey("OrdersModelID");

                    b.HasOne("IRSv2._0.Models.ToGoOrdersModel", null)
                        .WithMany("Products")
                        .HasForeignKey("ToGoOrdersModelID");
                });

            modelBuilder.Entity("IRSv2._0.Models.StorageItemsModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ProductsModel", null)
                        .WithMany("Items")
                        .HasForeignKey("ProductsModelID");
                });

            modelBuilder.Entity("IRSv2._0.Models.TablesModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.HostsModel", null)
                        .WithMany("Sector")
                        .HasForeignKey("HostsModelID");

                    b.HasOne("IRSv2._0.Models.OrdersModel", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.WaitersModel", null)
                        .WithMany("Sector")
                        .HasForeignKey("WaitersModelID");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IRSv2._0.Models.ToGoOrdersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.DeliverersModel", null)
                        .WithMany("ToGoOrders")
                        .HasForeignKey("DeliverersModelID");

                    b.HasOne("IRSv2._0.Models.HostsModel", null)
                        .WithMany("ToGoOrders")
                        .HasForeignKey("HostsModelID");
                });

            modelBuilder.Entity("IRSv2._0.Models.WaitersModel", b =>
                {
                    b.HasOne("IRSv2._0.Models.ManagersModel", null)
                        .WithMany("Waiters")
                        .HasForeignKey("ManagersModelID");
                });

            modelBuilder.Entity("IRSv2._0.Models.DeliverersModel", b =>
                {
                    b.Navigation("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.HostsModel", b =>
                {
                    b.Navigation("Sector");

                    b.Navigation("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.ManagersModel", b =>
                {
                    b.Navigation("Cooks");

                    b.Navigation("Deliverers");

                    b.Navigation("Hosts");

                    b.Navigation("Waiters");
                });

            modelBuilder.Entity("IRSv2._0.Models.OrdersModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IRSv2._0.Models.ProductsModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IRSv2._0.Models.ToGoOrdersModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IRSv2._0.Models.WaitersModel", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sector");
                });
#pragma warning restore 612, 618
        }
    }
}
