// <auto-generated />
using IRSv2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRSv2._0.Migrations
{
    [DbContext(typeof(IRSDbContext))]
    partial class IRSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookOrder", b =>
                {
                    b.Property<string>("CooksID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CooksID", "OrdersID");

                    b.HasIndex("OrdersID");

                    b.ToTable("CookOrder");
                });

            modelBuilder.Entity("CookToGoOrder", b =>
                {
                    b.Property<string>("CooksID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToGoOrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CooksID", "ToGoOrdersID");

                    b.HasIndex("ToGoOrdersID");

                    b.ToTable("CookToGoOrder");
                });

            modelBuilder.Entity("IRSv2._0.Models.Cook", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Cooks");
                });

            modelBuilder.Entity("IRSv2._0.Models.Deliverer", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Deliverers");
                });

            modelBuilder.Entity("IRSv2._0.Models.Host", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("IRSv2._0.Models.Manager", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("IRSv2._0.Models.Order", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("TableID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaiterID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("WaiterID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IRSv2._0.Models.Product", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ToGoOrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ToGoOrderID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IRSv2._0.Models.StorageItem", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("StorageItems");
                });

            modelBuilder.Entity("IRSv2._0.Models.Table", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WaiterID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("HostID");

                    b.HasIndex("OrderId");

                    b.HasIndex("WaiterID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("IRSv2._0.Models.ToGoOrder", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DelivererID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverPhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DelivererID");

                    b.HasIndex("HostID");

                    b.ToTable("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.Waiter", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnWork")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Waiters");
                });

            modelBuilder.Entity("CookOrder", b =>
                {
                    b.HasOne("IRSv2._0.Models.Cook", null)
                        .WithMany()
                        .HasForeignKey("CooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CookToGoOrder", b =>
                {
                    b.HasOne("IRSv2._0.Models.Cook", null)
                        .WithMany()
                        .HasForeignKey("CooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.ToGoOrder", null)
                        .WithMany()
                        .HasForeignKey("ToGoOrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IRSv2._0.Models.Cook", b =>
                {
                    b.HasOne("IRSv2._0.Models.Manager", null)
                        .WithMany("Cooks")
                        .HasForeignKey("ManagerID");
                });

            modelBuilder.Entity("IRSv2._0.Models.Deliverer", b =>
                {
                    b.HasOne("IRSv2._0.Models.Manager", null)
                        .WithMany("Deliverers")
                        .HasForeignKey("ManagerID");
                });

            modelBuilder.Entity("IRSv2._0.Models.Host", b =>
                {
                    b.HasOne("IRSv2._0.Models.Manager", null)
                        .WithMany("Hosts")
                        .HasForeignKey("ManagerID");
                });

            modelBuilder.Entity("IRSv2._0.Models.Order", b =>
                {
                    b.HasOne("IRSv2._0.Models.Waiter", null)
                        .WithMany("Orders")
                        .HasForeignKey("WaiterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IRSv2._0.Models.Product", b =>
                {
                    b.HasOne("IRSv2._0.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderID");

                    b.HasOne("IRSv2._0.Models.ToGoOrder", null)
                        .WithMany("Products")
                        .HasForeignKey("ToGoOrderID");
                });

            modelBuilder.Entity("IRSv2._0.Models.StorageItem", b =>
                {
                    b.HasOne("IRSv2._0.Models.Product", null)
                        .WithMany("Items")
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("IRSv2._0.Models.Table", b =>
                {
                    b.HasOne("IRSv2._0.Models.Host", null)
                        .WithMany("Sector")
                        .HasForeignKey("HostID");

                    b.HasOne("IRSv2._0.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSv2._0.Models.Waiter", null)
                        .WithMany("Sector")
                        .HasForeignKey("WaiterID");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IRSv2._0.Models.ToGoOrder", b =>
                {
                    b.HasOne("IRSv2._0.Models.Deliverer", null)
                        .WithMany("ToGoOrders")
                        .HasForeignKey("DelivererID");

                    b.HasOne("IRSv2._0.Models.Host", null)
                        .WithMany("ToGoOrders")
                        .HasForeignKey("HostID");
                });

            modelBuilder.Entity("IRSv2._0.Models.Waiter", b =>
                {
                    b.HasOne("IRSv2._0.Models.Manager", null)
                        .WithMany("Waiters")
                        .HasForeignKey("ManagerID");
                });

            modelBuilder.Entity("IRSv2._0.Models.Deliverer", b =>
                {
                    b.Navigation("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.Host", b =>
                {
                    b.Navigation("Sector");

                    b.Navigation("ToGoOrders");
                });

            modelBuilder.Entity("IRSv2._0.Models.Manager", b =>
                {
                    b.Navigation("Cooks");

                    b.Navigation("Deliverers");

                    b.Navigation("Hosts");

                    b.Navigation("Waiters");
                });

            modelBuilder.Entity("IRSv2._0.Models.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IRSv2._0.Models.Product", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IRSv2._0.Models.ToGoOrder", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IRSv2._0.Models.Waiter", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sector");
                });
#pragma warning restore 612, 618
        }
    }
}
